const ShopActionTypes = {
  // UPDATE_COLLECTIONS: "UPDATE_COLLECTIONS", // Not needed as now we use 'thunk'
  FETCH_COLLECTIONS_START: "FETCH_COLLECTIONS_START",
  FETCH_COLLECTIONS_SUCCESS: "FETCH_COLLECTIONS_SUCCESS",
  FETCH_COLLECTIONS_FAILURE: "FETCH_COLLECTIONS_FAILURE",
};

export default ShopActionTypes;
